DA2_SistemaEscolar2016/Models/Alumno.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace DA2_SistemaEscolar2016.Models
{
    public class Alumno
    {
        [Key] //Llave primaria con autoincremento 1 en 1
        public int noMatricula {get; set;}

        [Required]
        [MinLength(2)]
        [Display(Name = "Nombre")]
        public String nombre { get; set; }

        [Required]
        [Display(Name = "Apellido Paterno")]
        public String apellidoP { get; set; }

        [Required]
        [Display(Name = "Apellido Materno")]
        public String apellidoM { get; set; }
        
        [Required]
        [DisplayFormat(DataFormatString="{0:yyyy-MM-dd}",ApplyFormatInEditMode=true)]
        [Display(Name = "Fecha de Nacimiento")]
        [DataType(DataType.Date)]
        public DateTime fechaNac { get; set; }

        //Un alumno tiene un solo grupo
        public int grupoID { get; set; }
        public virtual Grupo grupo { get; set; }

        //A un alumno le pertenecen varios archivos
        public virtual ICollection<Archivo> archivos { get; set; }
    }
}

DA2_SistemaEscolar2016/Controllers/AlumnoController.cs
using DA2_SistemaEscolar2016.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace DA2_SistemaEscolar2016.Controllers
{
    [Authorize]
    public class AlumnoController : Controller
    {
        //Conectarnos a la BD
        ApplicationDbContext db = new ApplicationDbContext();

        [HttpPost]
        public ActionResult listar(String nombreBuscado)
        {
            var resultadoDeBusqueda = new List<Alumno>();
            if (!String.IsNullOrEmpty(nombreBuscado)) { 
                //Consultar la lista de alumnos
                resultadoDeBusqueda = db.alumnos.Include("archivos").Where(a => a.apellidoP.Contains(nombreBuscado) ||
                    a.apellidoM.Contains(nombreBuscado) || a.nombre.Contains(nombreBuscado)).ToList();
            }
            else
            {
                //Arrojar todos los datos
                //resultadoDeBusqueda = db.alumnos.Include("archivos").ToList();
                resultadoDeBusqueda = db.alumnos.Include("archivos").ToList();
            }
            //Pedirle a la vista que muestra el resultado en pantalla
            return View(resultadoDeBusqueda);
        }

        [HttpGet]
        public ActionResult listar()
        {

            //Consultar la lista de alumnos
            var todosLosAlumnos = db.alumnos.Include("archivos").ToList();

            //Pedirle a la vista que muestra el resultado en pantalla
            return View(todosLosAlumnos);
        }

        /*Este te muestra la paginac con la forma
         * para dar de alta un nuevo nuevo alumno*/
        [HttpGet]
        [Authorize(Roles="Admin, Capturista")]
        public ActionResult crear()
        {
            //Tomar los datos con los que rellenas la lista
            var grupos = db.grupos;
            //Crear la lista de seleccion
            SelectList grupoID = new SelectList(grupos, "grupoID", "nombreGrupo");
            //Se envia la lista de seleccion a la vista
            ViewBag.grupoID = grupoID;

            return View();
        }

        /*Este se encarga de recibir los datos del nuevo
         alumno y guardarlo*/
        [HttpPost]
        [Authorize(Roles = "Admin, Capturista")]
        public ActionResult crear(Alumno alumnoNuevo, 
            HttpPostedFileBase fotoUpload, bool enDetallesDeGrupo = false)
        {
            //Validar si el nuevo alumno es valido
            if(ModelState.IsValid){
                //Si se subio una foto
                if (fotoUpload != null && fotoUpload.ContentLength > 0)
                {
                    Archivo fotoPerfil = new Archivo(fotoUpload, "Perfil");
                    //Se lee el archivo para descomponerlo 
                    fotoPerfil.contenido = Archivo.httpPostedFileBaseToByteArray(fotoUpload);

                    //Se crea al vuelo una nueva lista de archivos que
                    //contenga solamente el unico archivo que acabamos de crear
                    alumnoNuevo.archivos = new List<Archivo> { fotoPerfil };
                }

                //Crear alumno
                db.alumnos.Add(alumnoNuevo);

                //Guardar cambios
                db.SaveChanges();

                //Regresar una vista, todo salio bien
                //Si estaba en pantalla de detalles de grupo
                if (enDetallesDeGrupo)
                    return RedirectToAction("detalles", "grupos", new { id = alumnoNuevo.grupoID });
                else
                    return RedirectToAction("listar");
            }
            //Si llegaste tan lejos, porque hay una bronca
            ViewBag.MensajeError = "Hubo un error, favor de verificar la informacion introducida";

            //Te devuelve a interntarlo de nuevo
            return View();
        }

        [HttpGet]
        [Authorize]
        [Authorize(Roles = "Admin")]
        public ActionResult eliminar(int id = 0)
        {
            //Se busca el alumno que se quiere eliminar
            var alumno = db.alumnos.Find(id);
            if (alumno == null)
            {
                return RedirectToAction("listar");
            }

            return View(alumno);
        }

        [HttpPost]
        [ActionName("eliminar")]
        [Authorize]
        [Authorize(Roles = "Admin")]
        public ActionResult confirmarEliminar(int noMatricula = 0)
        {
            //Se busca el alumno que se quiere eliminar
            Alumno alumno = db.alumnos.Find(noMatricula);

            if (alumno == null)
                return RedirectToAction("listar");

            //Elimina alumnos
            db.alumnos.Remove(alumno);

            //Ejecuta la lista de queries en la BD
            db.SaveChanges();

            return RedirectToAction("listar");
        }

        [HttpGet]
        [Authorize]
        [Authorize(Roles = "Admin, Capturista")]
        public ActionResult editar(int id=0)
        {
            var alumno = db.alumnos.Find(id);
            //Se busca el alumno con sus archivos incluidos
            //var alumno = db.alumnos.Include(f => f.archivos).SingleOrDefault(al => al.noMatricula == id);
            if (alumno == null)
            {
                return RedirectToAction("listar");
            }

            //Tomar los datos con los que rellenas la lista
            var grupos = db.grupos;
            //Crear la lista de seleccion
            SelectList grupoID = new SelectList(grupos, "grupoID", "nombreGrupo");
            //Se envia la lista de seleccion a la vista
            ViewBag.grupoID = grupoID;

            return View(alumno);
        }

        [HttpPost]
        [Authorize(Roles = "Admin, Capturista")]
        public ActionResult editar(Alumno alumnoEditado, HttpPostedFileBase fotoUpload)
        {
            if (ModelState.IsValid) { 
                //Si se recibio una foto
                if(fotoUpload!=null && fotoUpload.ContentLength>0){
                    String tipoArchivo = "Perfil";
                    //Se busca la foto del alumno editado
                    Archivo fotoPerfil = db.archivos.SingleOrDefault(ar => 
                        ar.noMatricula == alumnoEditado.noMatricula && ar.tipo == tipoArchivo);
                    //Si existe la foto
                    if (fotoPerfil.archivoID>0) {
                        fotoPerfil.contenido = Archivo.httpPostedFileBaseToByteArray(fotoUpload);

                        //Se modifica el registro de la foto
                        db.Entry(fotoPerfil).State = EntityState.Modified;
                    }
                    else //Si no existe la foto
                    {
                        //Se crea una nueva
                        fotoPerfil = new Archivo(fotoUpload, tipoArchivo);
                        fotoPerfil.contenido = Archivo.httpPostedFileBaseToByteArray(fotoUpload);
                        //Y se relaciona con el alumno editado
                        fotoPerfil.noMatricula = alumnoEditado.noMatricula;
                        db.archivos.Add(fotoPerfil);
                    }
                }

                //Modificar el registro actual
                db.Entry(alumnoEditado).State = EntityState.Modified;
                db.SaveChanges();
                //Si llega tan lejos, es que todo salio bien
                return RedirectToAction("listar");
            }

            //Si llego hasta aca, es que algo es invalido
            //Lo regresas al formulario para corregir
            return View();
        }
    }
}

DA2_SistemaEscolar2016/Controllers/ArchivoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DA2_SistemaEscolar2016.Models;

namespace DA2_SistemaEscolar2016.Controllers
{
    public class ArchivoController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Archivo
        public FileResult download(int id =0)
        {
            var archivo = db.archivos.Find(id);
            return File(archivo.contenido, archivo.formatoContenido);
        }
    }
}

DA2_SistemaEscolar2016/Views/Alumno/Partial_Crear.cshtml
@model DA2_SistemaEscolar2016.Models.Alumno

@using (Html.BeginForm("crear","alumno",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()

    <div>
        <h4>Nuevo Alumno</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model=>model.grupoID)
        <input type="hidden" name="enDetallesDeGrupo" value="true" />
        <div class="row">
            <div class="form-group col-md-6">
                @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>

            <div class="form-group col-md-6">
                @Html.LabelFor(model => model.apellidoP, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.apellidoP, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.apellidoP, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-6">
                @Html.LabelFor(model => model.apellidoM, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.apellidoM, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.apellidoM, "", new { @class = "text-danger" })
            </div>

            <div class="form-group col-md-6">
                @Html.LabelFor(model => model.fechaNac, htmlAttributes: new { @class = "control-label" })
                @Html.EditorFor(model => model.fechaNac, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fechaNac, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            <div class="form-group">
                <div class="col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
}
<hr />

DA2_SistemaEscolar2016/Views/Alumno/crear.cshtml
@model Alumno
@using DA2_SistemaEscolar2016.Models

@{
    ViewBag.Title = "crear";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>crear</h2>
@using (Html.BeginForm("crear", "Alumno",
    FormMethod.Post, new { enctype="multipart/form-data" }))
{
    <div class="row">
        <div class="form-group col-sm-6">
            @Html.LabelFor(a => a.nombre)
            @Html.EditorFor(a => a.nombre,
        new { htmlAttributes = new { required = "", @class = "form-control", placeholder = "Nombre" } })
            @Html.ValidationMessageFor(a => a.nombre, "", new { @class = "error" })
        </div>
        <div class="form-group col-sm-6">
            @Html.LabelFor(a => a.apellidoP)
            @Html.EditorFor(a => a.apellidoP,
        new { htmlAttributes = new { required = "", @class = "form-control", placeholder = "Apellido Paterno" } })
            @Html.ValidationMessageFor(a => a.apellidoP, "", new { @class = "error" })
        </div>
    </div>

    <div class="row">
        <div class="form-group col-sm-6">
            @Html.LabelFor(a => a.apellidoM)
            @Html.EditorFor(a => a.apellidoM,
        new { htmlAttributes = new { required = "", @class = "form-control" } })
            @Html.ValidationMessageFor(a => a.apellidoM, "", new { @class = "error" })
        </div>
        <div class="form-group col-sm-6">
            @Html.LabelFor(a => a.fechaNac)
            @Html.EditorFor(a => a.fechaNac,
        new { htmlAttributes = new { required = "", @class = "form-control" } })
            @Html.ValidationMessageFor(a => a.fechaNac, "", new { @class = "error" })
        </div>
    </div>
    <div class="row">
        <div class="form-group col-sm-6">
            @Html.LabelFor(a => a.grupo.nombreGrupo)
            @Html.DropDownList("grupoID", null, new { @class = "form-control" })
        </div>
        <div class="form-group col-sm-6">
            <label for="fotoUpload">Fotografia</label>
            <input id="fotoUpload" name="fotoUpload" type="file" class="form-control" accept="image/*">
        </div>
    </div>
    <button class="btn btn-primary" type="submit">Enviar</button>
    @*<div class="error">@Html.ValidationSummary()</div>*@
}

DA2_SistemaEscolar2016/Views/Alumno/editar.cshtml
@model Alumno
@using DA2_SistemaEscolar2016.Models
@{
    ViewBag.Title = "editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
    
    //Determinar el id de la foto del usuario q editaremos
    int archivoID=0;
    if (Model.archivos.Count >0)
    {
         archivoID = Model.archivos.FirstOrDefault(foto => foto.tipo == "Perfil").archivoID;
    }
}

<h2>editar</h2>
@using (Html.BeginForm("Editar", "alumno", FormMethod.Post, new { enctype="multipart/form-data"}))
{ 
    @Html.HiddenFor(a => a.noMatricula)
    <div class="row">
        <div class="col-sm-6">
            <div class="form-group col-sm-12">
                @Html.LabelFor(a => a.nombre)
                @Html.EditorFor(a => a.nombre,
        new { htmlAttributes = new { required = "", @class = "form-control", placeholder = "Nombre" } })
                @Html.ValidationMessageFor(a => a.nombre, "", new { @class = "error" })
            </div>
            <div class="form-group col-sm-12">
                @Html.LabelFor(a => a.apellidoP)
                @Html.EditorFor(a => a.apellidoP,
        new { htmlAttributes = new { required = "", @class = "form-control", placeholder = "Apellido Paterno" } })
                @Html.ValidationMessageFor(a => a.apellidoP, "", new { @class = "error" })
            </div>

            <div class="form-group col-sm-12">
                @Html.LabelFor(a => a.apellidoM)
                @Html.EditorFor(a => a.apellidoM,
        new { htmlAttributes = new { required = "", @class = "form-control" } })
                @Html.ValidationMessageFor(a => a.apellidoM, "", new { @class = "error" })
            </div>
            <div class="form-group col-sm-12">
                @Html.LabelFor(a => a.fechaNac)
                @Html.EditorFor(a => a.fechaNac,
        new { htmlAttributes = new { required = "", @class = "form-control" } })
                @Html.ValidationMessageFor(a => a.fechaNac, "", new { @class = "error" })
            </div>

            <div class="form-group col-sm-12">
                @Html.LabelFor(a => a.grupo.nombreGrupo)
                @Html.DropDownList("grupoID", null, new { @class = "form-control" })
            </div>
        </div>
        <!--INPUT FILE-->
        <div class="form-group col-sm-6">
            <label for="fotoUpload">Fotografia</label>
            <input id="fotoUpload" name="fotoUpload"
                   onchange="readURL(this)" type="file" class="form-control" accept="image/*">
        </div>

        <!--LA FOTO DEL USUARIO-->
        <div>
            @if (archivoID > 0)
            {
                <img id="imgAlumno" src="@Url.Action("download","Archivo", new { id = archivoID } )" />
            }
            else
            {
                <img id="imgAlumno" src="/Content/img/sinfoto.gif" />
            }
        </div>

        <button class="btn btn-primary" type="submit">Enviar</button>
    </div>
}
@section scripts{
<script>
   function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#imgAlumno')
                    .attr('src', e.target.result)
            };

            reader.readAsDataURL(input.files[0]);
        }
    }
    </script>
}

DA2_SistemaEscolar2016/Views/Alumno/eliminar.cshtml
@model Alumno
@using DA2_SistemaEscolar2016.Models

@{
    ViewBag.Title = "eliminar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>eliminar</h2>
<p>¿Esta seguro que desea eliminar el siguiente alumno?</p>
<span>Nombre: </span>@(Model.nombre+" "+Model.apellidoP+" "+Model.apellidoM)<br />
<span>Grupo: </span>@Model.grupo.nombreGrupo

<form action="confirmarEliminar" method="post">
    @Html.HiddenFor(cosa=>cosa.noMatricula)
    <button type="submit">Confirmar</button>
</form>

DA2_SistemaEscolar2016/Views/Alumno/listar.cshtml
@*Esta vista tiene como objeto principal una lista de alumnos*@
@model List<Alumno>
@using DA2_SistemaEscolar2016.Models

@{
    ViewBag.Title = "listar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>listar</h2>

@Html.Partial("../BuscadorFormulario")

@if (User.IsInRole("Admin")||User.IsInRole("Capturista"))
{
    @Html.ActionLink("Nuevo Alumno","crear")
}
<table class="table table-striped table-hover">
    <tr>
        <th>Matricula</th>
        <th>Nombre Completo</th>
        <th>Fecha Nacimiento</th>
        <th>Grupo</th>
        <th>Foto</th>
    </tr>
    @foreach (var alumno in Model.OrderBy(al=>al.fechaNac)) {
        int fotoPerfilID = 0;
        if (alumno.archivos.Count > 0) {
            fotoPerfilID = alumno.archivos.FirstOrDefault(foto => foto.tipo == "Perfil").archivoID;
        }
        <tr>
            <td>@alumno.noMatricula</td>
            <td>@(alumno.nombre + " " + alumno.apellidoP + " " + alumno.apellidoM)</td>
            <td>@alumno.fechaNac.ToLongDateString()</td>
            <td>@alumno.grupo.nombreGrupo</td>
            <td>
                @if (fotoPerfilID == 0)
                {
                    <img src="/Content/img/sinfoto.gif" />
                }
                else
                {
                    <img src="@Url.Action("download", "Archivo", new { id = fotoPerfilID })" />
                }
            </td>
            <td>
                @if (User.IsInRole("Admin"))
                {
                    @Html.ActionLink("Eliminar", "eliminar", new { id = alumno.noMatricula })
                    @(" | ")
                }
                
                @if (User.IsInRole("Admin") || User.IsInRole("Capturista"))
                {
                    @Html.ActionLink("Editar", "editar", new { id = alumno.noMatricula })
                }
                
            </td>
        </tr>
    }
</table>